services:
  app:
    build: ./app
    ports:
      - "8000:8000"
    env_file:
      - path: ./app/.env
        required: false
    restart: unless-stopped


  scrapers:
    build: ./scrapers
    env_file:
      - path: ./scrapers/.env
        required: false
    environment:
      SCRAPE_INTERVAL_SECONDS: "21600"
      RUN_ON_START: "true"
      HEADLESS: "true"
    volumes:
      - ./scrapers/scrapers:/app/scrapers
    restart: unless-stopped
